name: Cargo build

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - edev
  pull_request:
    branches:
      - edev

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
